assassinapp/urls.py
#Configure URLs for assassins app

from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^register$', views.registerView, name='register'),
    url(r'^$', views.homeView, name='home'),
    url(r'^obliterate/(?P<uuid>[\w]+)$', views.obliterateNick, name='obliterate')
]

assassins/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^assassins/', include('assassinapp.urls', namespace='assassins'))
]

assassinapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User, AnonymousUser

from datetime import timedelta

from uuid import uuid4

# Create your models here.

class PlayerObject(models.Model):
    user = models.OneToOneField(to=User, default=0)
    nick = models.CharField(default="Supreme assassin", max_length=32)
    uuid = models.CharField(max_length=36, default=str(uuid4()))
    creation_timestamp = models.DateTimeField(default=timezone.now())
    expiration_timestamp = models.DateTimeField(default=timezone.now()+timedelta(days=1))

    def __str__(self):
        return str(self.nick)

class LobbyObject(models.Model):
    host = models.OneToOneField(PlayerObject, on_delete=models.CASCADE, related_name='host')
    players = models.ForeignKey(PlayerObject, related_name='lobby_players')
    lobby_uuid =  models.CharField(max_length=36, default=str(uuid4()))
    creation_timestamp = models.DateTimeField(default=timezone.now())
    expiration_timestamp = models.DateTimeField(default=timezone.now()+timedelta(hours=2))
    key = models.CharField(max_length=24, null=True)



class GameObject(models.Model):
    lobby = models.OneToOneField(LobbyObject, on_delete=models.CASCADE, null=True)
    is_idle = models.BooleanField(default=True)
    is_active = models.BooleanField(default=False)

assassinapp/forms.py
from django import forms


class RegisterForm(forms.Form):
    nick = forms.CharField(label='nickname', max_length=32)

    class Meta:
        classname = 'RegisterForm'

assassinapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.contrib.auth import authenticate, login, logout
from forms import *
from models import *

from uuid import uuid4

# Create your views here.

def homeView(request):
    return render(request, 'home.html')

def registerView(request, **kwargs):        
    if request.method == 'GET':
        register_form = RegisterForm()
        return render(request, 
                'register.html',
                {'register_form': register_form})
    if request.method == 'POST':
        ## Validate form code
        form_data = RegisterForm(request.POST)
        if form_data.is_valid():
            player_uuid = str(uuid4)
            user = User.objects.create(
                        username=player_uuid,
                        password='default'
            )
            user.save()
            player = PlayerObject(
                        user=user,
                        nick=request.POST['nick'],
                        uuid=player_uuid,
            )
            player.save()
            authenticated_user = authenticate(username=user.username, password=user.password)
            login(request, user)
        return HttpResponseRedirect('/assassins')

def createLobbyView(request):
    pass

                
    
def joinGameView(request):
    pass

def obliterateNick(request, uuid=None):
    print(uuid)
    player = User.objects.get(username=uuid)
    nick_object = player.playerobject
    logout(request)
    player.delete()
    nick_object.delete()
    return HttpResponseRedirect('/assassins')

templates/home.html
 <head>
    <style>
        body {
            background-color:crimson
        }
    </style>
    <script type="javascript" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
</head>
{% if user.is_authenticated %}
<h1>Welcome to Assassins, {{ user.username }}.</h1>

<p>Click here to create a new lobby.</p>

<form action='{% url "assassins:obliterate" uuid=user.username %}'' method="DELETE">
    <input type="submit" value="Obliterate nickname">
</form>

{% else %}
<h1>Welcome to Assassins.</h1>
<p>Navigate to <a href="{% url 'assassins:register' %}">/assassins/register</a> to register a nickname.</p>
{% endif %}

templates/register.html
<head>
    <style>
        body {
            background-color:crimson
        }
    </style>
</head>
<h1>Welcome to Assassins</h1>
<h2>Register your nick here.</h2>
<form method="POST" action="/assassins/register">
    {% csrf_token %}
    {{ register_form }}
    <input type="submit">
</form>